drop table REFERENCE_DATA;

CREATE TABLE REFERENCE_DATA
(
   seq int PRIMARY KEY NOT NULL AUTO_INCREMENT,
   id int NOT NULL,
   code varchar(100) NOT NULL,
   description varchar(100) NOT NULL,
   type varchar(20) NOT NULL,
   modify_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX REF_DATA_01 ON REFERENCE_DATA(seq);
CREATE UNIQUE INDEX REF_DATA_02 ON REFERENCE_DATA (id);
CREATE UNIQUE INDEX REF_DATA_03 ON REFERENCE_DATA (code);